[alpha_vantage]
api_key = "NEP7RZO5JVFHL1K6"
 
[openai]
api_key = "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"
 
[bespoke_labs]
api_key = "bespoke-c224edb7dd0df5a2459d688c316e160b28c3bcaab7c0474771fe326ae3cfe8dc"
 
