api_key='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'
openai='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'

